[platformio]
default_envs = waveshare_esp32_s3_zero

;------------------------------------------------------------------
[env:esp32-s3-devkitc-1] ; for official ESP32-S3 DevKitC-1 n8r8
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM

board_build.arduino.memory_type = qio_opi

board_upload.flash_size = 8MB

lib_deps =
    fastled/FastLED @ ^3.9.14

;------------------------------------------------------------------
[env:waveshare_esp32_s3_zero] ; for Waveshare ESP32-S3 Zero n4r2
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_upload.flash_size = 4MB
board_build.partitions = default.csv
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_qspi  ; Uses external QSPI PSRAM, not OPI like the ESP32-S3 DevKitC-1

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
    
upload_port = COM7

lib_deps =
    fastled/FastLED @ ^3.9.14

;------------------------------------------------------------------
[env:esp32dev] ; for ESP32 DevKitC boards without PSRAM, like the original ESP32 DevKitC V4
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino

; change microcontroller
board_build.mcu = esp32

; change MCU frequency
board_build.f_cpu = 240000000L

lib_deps =
    fastled/FastLED @ ^3.9.14